version: '3.8'

services:
#БД
  db:
    image: postgres:15-alpine
    container_name: gym_db
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Брокер повідомлень (для Celery)
  redis:
    image: redis:7-alpine
    container_name: gym_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
