services:

#Веб
  web:
    build: .             #Dockerfile у папці
    container_name: vertex_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app           #зміни коду на комп'ютері миттєво видно в контейнері
    ports:
      - "8000:8000"      #порт назовні
    env_file:
      - .env             #змінні
    depends_on:
      db:
        condition: service_healthy #поки база гуд
      redis:
        condition: service_started

#БД
  db:
    image: postgres:15-alpine
    container_name: gym_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Брокер повідомлень (для Celery)
  redis:
    image: redis:7-alpine
    container_name: gym_redis
    ports:
      - "6379:6379"

  pg_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: pg_exporter
    environment: 
      DATA_SOURCE_NAME: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    ports:
      - "9187:9187"
    # Потребує того ж network, що й db

  #prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus #зберігання історичних даних
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  #grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # node_exporter:
  #   image: prom/node-exporter
  #   container_name: node_exporter
  #   #дозволяє бачити метрики всієї системи
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
  #   #повинен працювати як хост для збору
  #   network_mode: host

volumes:
  pg_data:
  prometheus_data:
  grafana_data:
