services:

#Веб
  web:
    build: .             # <--- Каже: "Шукай Dockerfile у цій же папці і збери образ"
    container_name: vertex_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app           # <--- Магія: зміни коду на комп'ютері миттєво видно в контейнері
    ports:
      - "8000:8000"      # Прокидаємо порт назовні
    env_file:
      - .env             # Читаємо змінні
    depends_on:
      db:
        condition: service_healthy # Чекаємо, поки база прокинеться
      redis:
        condition: service_started

#БД
  db:
    image: postgres:15-alpine
    container_name: gym_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Брокер повідомлень (для Celery)
  redis:
    image: redis:7-alpine
    container_name: gym_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
