global:
  scrape_interval: 15s

rule_files:
  - 'rules/*.yml'

scrape_configs:
  #Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  #Django
  - job_name: 'django_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8000'] 

  #Postgres
  - job_name: 'postgres'
    static_configs:
      - targets: ['pg_exporter:9187']

#  #EC2-інстанс: CPU, RAM, Disk
#   - job_name: 'node_exporter'
#     static_configs:
#       - targets: ['localhost:9100']