$ANSIBLE_VAULT;1.1;AES256
30386465653466333231373830623139623432643735323935613335656435653037366361303366
3531666131333161323361663233373061323865666466650a373033636433396264623565393632
36633066613465306163353864346431313530626437643739616461656230623339363339633234
6539323462313739350a656162626538333434353066383537356537613036313536393333643836
31393563323636313861383739343934303435386262323033613437646262643038663136356162
34373435393863313065663336356336303035616233303564306161383939353861323865656563
39313738653536313932363231343737393964393161656365373137343766616437383035366362
65323666313933366134323234353666303430313631386662623365326235383565366132643936
64613133613234656364313830633261346531303963313466653361373438663834353438623063
37643762356338303634623038366233336636313730333331643537383135626135363065393461
62653234643864633166373565386136343461366236336664663066653536343839613564646264
32336565316532363365313734633662393039313165633561376265303162303333356661373462
39663663653338366461383436613463316161643162313232376232306335393233363637363865
33623731376234383462393362366230383462653363303934313733323231613537323930373461
303335633563336635376662333266666261
