$ANSIBLE_VAULT;1.1;AES256
66343264663038316530623535356533646239653638316236383334383536646565626434313364
3538303165386664386365363936666663376338376532310a323562613364613361626535613061
32326430373730663063613062653539393035636139366362333131366334323366303835356236
3361643662333263610a646332666566663832613137353330323331666230653139663765656132
32306230366634363638383331376139383664646134646136326534393131346638633166643034
37643830663461386335616463623762613239616361303230333832663135393532633938656135
31303862653438333063333730343130373162343537343132323437313136313339333130376639
64656461313331343230343037363961646665636533383061656261363363643538303930346338
38393965663732633962313836336362656134326238336261396330663130363062366432346430
66306265666134316238363438313634633566666262396663336335393662393564356539346538
30666563373661623263626236616331336361356662653565306537336666646162306132303433
35393531313132336338373834363664333232373437363561623961336338636438363065636264
39353731373330346439313332306162363965616230306164376539613233313466616132386163
6230353939373063353139326238343230343362326432396535
