- name: Include encrypted secrets from vars/secrets.yml
  ansible.builtin.include_vars:
    file: secrets.yml

- name: Ensure community.docker collection is installed
  ansible.builtin.command: ansible-galaxy collection install community.docker
  run_once: true
  delegate_to: localhost
  become: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - git
      - docker.io
    state: present
  become: true

- name: Install Docker Compose V2 via official shell script
  ansible.builtin.shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
  become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Clone/Update repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ project_dir }}"
    version: main
    force: yes

# .env з шаблону
#власник може читати
- name: Create .env file from template
  template:
    src: .env.j2
    dest: "{{ project_dir }}/.env"
    mode: '0600'

- name: Start Docker Compose (Shell Fallback)
  ansible.builtin.shell: |
    /usr/local/bin/docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ project_dir }}"
  become: true
